ElvUI/Core/Modules/Nameplates/StyleFilter.lua
Buffs and debuffs would bleed through the style filter because source was not being reevaluated correctly which would result in the FromMe/FromPet filters not applying correctly and triggering on buffs/debuffs from other players if you are in combat with the same target. This PR fixes that.
=> Fix "source" not being reassigned

ElvUI/Core/Modules/UnitFrames/ConfigEnviroment.lua
Limit number of players shown if 'display player' option is disabled
=> Number of units in test frame

ElvUI/Core/Modules/Chat/Chat.lua
Amends 042fbb0 as described by a1819c7
Yes, it is still getting shuffled. You can witness the bug as described in #272
TL;DR: Reload UI. ChatEditHistory in character SavedVars is now reordered. It shouldn't be doing that.
It can be fixed either by removing the AddHistoryLine block, or by hooking AddHistoryLine *after* that section. Both should probably be done anyway, so I've done both. Reminder that the default EditBox history is overwritten by ElvUI and is never used (ElvUI also wipes it constantly), so removing AddHistoryLine does not break chat edit history.
=> Fixes chat edit history getting shuffled

ElvUI/Core/Modules/Maps/Minimap.lua
Prevent the minimap from shifting left a pixel when scaling up to 200%
=> Fix minimap anchor when scaling

ElvUI/Core/Modules/DataTexts/Intellect.lua
Issue:
Changed to match how the other ability datatexts are coded.
=> Fix Intellect DT's default label

ElvUI/Wrath/Modules/DataTexts/DualSpec.lua, ElvUI/Wrath/Modules/DataTexts/Load_DataTexts.xml
Example:
On character without dual spec:
On character below level 10 (could change this to be `N/A`?):
Something to note:
I can not remember the proper way to add the NoLabel global for a datatext that is only in Wrath, so I will leave that to whomever wants to do it.
=> Adding Dual Spec Datatext

ElvUI/Libraries/Core/LibDualSpec-1.0/LibDualSpec-1.0.lua
I was getting the following error in Wrath:
```
Message: ...I\Libraries\Core\LibDualSpec-1.0\LibDualSpec-1.0.lua:470: attempt to compare number with string
Time: Fri Oct 14 14:50:22 2022
Count: 2
Stack: ...I\Libraries\Core\LibDualSpec-1.0\LibDualSpec-1.0.lua:470: attempt to compare number with string
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Libraries\Core\LibDualSpec-1.0\LibDualSpec-1.0.lua"]:470: in function <...I\Libraries\Core\LibDualSpec-1.0\LibDualSpec-1.0.lua:451>
Locals: 
```
The global GetSpecialization function was returning the spec ID as a string. Using the LibClassicSpecs version if it exists fixed the error.
=> Use LibClassicSpecs GetSpecialization in LibDualSpec

ElvUI/Core/Modules/Bags/Bags.lua, ElvUI/Core/Modules/Bags/Sort.lua, ElvUI/Core/Modules/Tooltip/Tooltip.lua
Fix Tooltip OnTooltipSet and Bag Sort for 10.0.2
* use TooltipDataProcessor.AddTooltipPostCall for
* OnTooltipSetSpell
* OnTooltipSetItem
* OnTooltipSetUnit
* Copy C_Container workarounds to Sort and use new C_Container.GetContainerItemInfo
=> Fix Tooltip OnTooltipSet and Bag Sort

ElvUI/Libraries/Core/oUF/elements/classpower.lua
UnitPower and UnitPowerMax have a 3rd parameter to get a full value, mainly for destro locks and their partial soul shards.
Tested on (PTR):
Lock - Destro + Aff
Rogue
=> Fix classpower bar

ElvUI/Core/General/Install.lua, ElvUI_OptionsUI/ActionBars.lua
keyDown is already defaulted to 1 in profile.lua
Players may have to toggle it twice to get it to sync up if they edited the cvar outside of this.
=> Fix issue when players try to move spells

ElvUI/Core/Defaults/Profile.lua, ElvUI_OptionsUI/UnitFrames.lua
This pull request adds the previously missing options to configure the castbar positions for arena unit frames, in the same way it already works for party frames.
=> Add missing arena castbar position options

ElvUI/Core/Modules/ActionBars/ActionBars.lua
We should allow Masque skins to apply their mask to the buttons so that unique shapes can still be achieved.
=> Fix Masque skin masks not applying

ElvUI/Mainline/Modules/Skins/Macro.lua
=> MacroFrame top tab text not vertically centered

ElvUI_Libraries/Core/LibDispel/LibDispel.lua
Evoker's Cauterizing Flame talent is a 1 minute CD that dispels Bleeds, Poisons, Curses, and Diseases. This change adds support for all of those effects except the Bleed dispel, since as far as I can tell, bleed dispels do not seem to be supported in this module yet.
Tested for disease dispel by taking the talent, being in a party, and getting a disease.
=> Add Evoker Cauterizing Flame dispel support

ElvUI/Core/Modules/DataTexts/Crit.lua, ElvUI/Mainline/Modules/DataTexts/Mastery.lua
Just adding this because I use a custom panel with all 4 of the secondary stat datatexts on it and crit didn't have a tooltip, and mastery never showed your rating. This was how i checked for ratings when comparing raw values between stats.
I couldn't find/figure out the class/base tooltip for crit, so I would appreciate some feedback on that if possible.
=> feat: add rating tooltip lines to crit and mastery

ElvUI/Core/Modules/Tooltip/Tooltip.lua
The first issue of function `TT:PopulateInspectGUIDCache` are listed in the comments.
Second issue about function `TT:INSPECT_READY` is as below:
(1) mouseover a unit and press shift
(2) `TT.GameTooltip_OnTooltipSetUnit` call function `TT:AddInspectInfo`
(3) `TT:AddInspectInfo` call `NotifyInspect(unit)` but sometimes it will not success, `itemLevel` will return false in `E:GetUnitItemLevel('mouseover')`. But `lastGUID` in `TT:AddInspectInfo` is now equal to `unitGUID`, so `NotifyInspect` will never called later. Then it will fall into a loop.
=> Fix two issues of InspectInfo in Tooltip.lua

ElvUI/Mainline/Filters/Filters.lua
Orbital strike combined with incarnation: chosen of elune has a different spell id
=> Add Orbital Strike to druid playerbuffs

ElvUI/Mainline/Filters/Filters.lua
This is a strong defensive offered by evoker and should be tracked
=> Add Evoker Time Dilation to TurtleBuffs

ElvUI/Core/Modules/Tooltip/Tooltip.lua
This PR is fixing issue with #1155
**UnitPVPName** in some cases returns empty value instead of **nil**
=> Fix issue with Tooltip not showing player names

ElvUI/Core/Modules/Misc/EditorMode.lua
Swapped RefreshAuraFrame to RefreshBuffsAndDebuffs. Not sure if it was changed but RefreshAuraFrame is no longer in Blizzard code.
=> Retail: Fix Aura function name in EditorMode.

ElvUI_Libraries/Core/oUF_Plugins/oUF_EnergyManaRegen.lua
Fixing bug where 0 cost abilities (like Wrath when empowered by Fury of Stormrage) would cause the 5 second rule visual ticker to reset after a cast instead of continuing to tick. 
https://github.com/tukui-org/ElvUI/issues/1146
=> Update oUF_EnergyManaRegen.lua Mana Tick

ElvUI/Mainline/Modules/Skins/BGMap.lua
I've made a few improvements/fixes here:
1. Set a default scale level on the zone map, so that it's not giga-zoomed when you open it:
2. Mark that the frame has been moved by the player, so that its saved in the layout cache. This fixes this awkward position jumping that occurs:
https://imgur.com/a/9nLeP1d
3. Only allow the zone map to be moved using the tab. When you're zoomed in on the zone map, click-dragging is required in order to pan the map around. You cannot overlap functionality here, by attempting to allow the user to simultaneously move the frame. By doing so, you create this odd behavior where the map texture remains static as the scroll container moves over-top of it:
https://imgur.com/a/a3aprpW
=> Battlefield map improvements

ElvUI_Options/Core/StyleFilters.lua
In the Nameplates/Style Filters options, the dropdown list is sorted by the first character. This means that styles with a priority starting with 1 (such as 10, 18, and 100) will be higher in the list than styles with a priority starting with 2 (like 2, 25, and 29).
This pull request adds a function to the options table to sort the list by the priority of the style.
I decided to keep with style and make it one line. But for the curious here is the function in a more readable format:
```lua
StyleFilters.selectFilter.sorting = function()
wipe(sortedFilters)
local list = E.global.nameplates.filters
for filter in next, list do 
tinsert(sortedFilters, filter)
end
sort(sortedFilters, function(a, b) 
return list[a].triggers.priority < list[b].triggers.priority
end)
return sortedFilters
end
``` …
=> Sort nameplate style filter dropdown by priority

ElvUI_Options/Core/General.lua
Increase maximum allowed option value for top and bottom panel heights from 128px to 256px. In my case, I like a big bottom panel, at 140px currently. So if 256px seems to much, I'm open to reducing it a bit more.
=> Increase the maximum heights for top and bottom cosmetic panels

ElvUI/Core/Modules/Chat/Chat.lua
When the chat module is disabled, don't re-color the `ChatFrame` tabs.
There does not seem to be a Blizzard skin for the chat frames, so coupling this to the state of the chat module seems the best option.
=> Don't color chat tabs when chat module is disabled

ElvUI/Core/Modules/DataTexts/DataTexts.lua
ElvUI triggers an error when hovering over a LDB plugin with a custom tooltip:
```
37x ...ceElvUI/Core/Modules/DataTexts/DataTexts.lua:334: attempt to call method 'GetParent' (a nil value)
[ElvUI/Core/Modules/DataTexts/DataTexts.lua]:334: in function <...ceElvUI/Core/Modules/DataTexts/DataTexts.lua:333>
[tail call]: ?
[ElvUI/Core/Modules/DataTexts/DataTexts.lua]:221: in function 'func'
[ElvUI/Core/Modules/DataTexts/DataTexts.lua]:101: in function <...ceElvUI/Core/Modules/DataTexts/DataTexts.lua:91>
[tail call]: ?
```
`SetupTooltip()` expects a frame, but `self` within `OnEnter` refers to `DT` - the DataTexts module itself.
=> fix SetupTooltip parameter for LDB plugins with custom tooltip

ElvUI_Options/Core/UnitFrames.lua
Setting the text positions for each aura indicator I'd like to be tracked on my unit frames is tiresome. Luckily, a base already exists for applying options to every aura.
Let's expand the "Apply To All" section on the "Aura Indicator" unitframe options to also include settings for the count text and the cooldown text. This makes it easier to adjust all the text positions inside the textured icon for all auras at once.
Tested with retail and ElvUI 13.87.
=> Add "Count Text" and "Cooldown Text" options to the "Apply To All" Aura Indicator section

ElvUI/Core/Modules/Misc/ChatBubbles.lua
I use a few addons that hide certain NPC's chat bubbles. They seem to do the same thing of hiding the children of the chat bubble frame. But since the name text is parented to the frame and not the child frame, its not hidden. Leaving a floating name.
=> Parent chat bubble name to holder

ElvUI/Core/General/Tags.lua
Add a tag that only displays the first word—handy for non-English languages like French, where word order is reversed.
=> Added [name:first]
